遇到的问题.md

###### 请求登录post 报 404

没有添加header头，按照Chrome的报文格式添加相应的信息
```
header = {
	'Referer':'https://segmentfault.com/a/1190000002507299',
	'Host':'segmentfault.com',
	'Cookie':'PHPSESSID=web3~fdf535b2518f7f061780d987bb65934a; showRegister2=true; showRegister=false; _gat=1; io=eTK6St1K6padW---DrVi; _ga=GA1.2.613128477.1495522770; _gid=GA1.2.930526416.1508135759; Hm_lvt_e23800c454aa573c0ccb16b52665ac26=1507606967,1507816841,1508135889; Hm_lpvt_e23800c454aa573c0ccb16b52665ac26=1508136235',
	'User-Agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36'
}
```


###### Chrome 开发者工具暂停功能

command + E 

###### 函数

len()：返回输入字符串的长度（字符的个数）
str()：将输入变量转为字符串
int()：将输入变量转为数字


###### pip install mechanize occur:

```
pip install mechanize

Uninstalling setuptools-1.1.6:
Exception:
Traceback (most recent call last):
```

增加 `--user python`
```
➜  python git:(master) ✗ pip install mechanize --user python
```


###### 中文无法解析

SyntaxError: Non-ASCII character '\xe6' but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

```
# -*- coding: utf-8 -*-
```

[https://stackoverflow.com/questions/3170211/why-declare-unicode-by-string-in-python](https://stackoverflow.com/questions/3170211/why-declare-unicode-by-string-in-python)

###### UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 20: ordinal not in range(128)

```
encode('utf-8').strip()
```


###### 如何在一个函数里用全局变量?

如果你要在别的函数里使用全局变量,只要在被调用全局变量函数的里事先用global声明一下:

```
globvar = 0

def set_globvar_to_one():
    global globvar    # 需要用global修饰一下globvar
    globvar = 1

def print_globvar():
    print globvar     # 如果要读globbar的值的话不需要用global修饰

set_globvar_to_one()
print_globvar()       # 输出 1
```

###### requests.exceptions.SSLError: HTTPSConnectionPool

打开 shawosock 自动代理就好了

###### mac 安装信任证书

charles - help - ssl proxying - install charles root certification

在证书管理中 - 搜索charles - 双击弹开窗 - 点击受信任


###### 需要验证码登录 、 登录频繁请求

- orc 图像识别
- 下载手动录入
- cookie 更新 避免验证码
- post请求数据错了


###### 知乎：验证码会话失效

获取验证的代码写在 a.py
登录的代码写在 b.py

导致cookie信息不一致 ， 尝试在 b.py中使用a.py保存在文件的cookie 但是cookie两次请求的cookie不一致 一样会导致登录失败

######  requests.exceptions.ConnectionError: HTTPSConnectionPool(host='segmentfault.com', port=443): Max retries exceeded with url:   (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1028ff9d0>: Failed to establish a new connection: [Errno 60] Operation timed out',))



###### 引入模块
from preCaptcha import CaptchaHelper

cap = CaptchaHelper()
cap.zhihu()


###### headers.cookie =连接的是键值对

requests.session().cookies是json格式



```
		# 获取验证码图片访问得到的 cookies
		# file = open('zhihu_cookies','r')
		# cookies = json.load(file)
		# self._session.cookies.update(cookies)
```