###### 异常的处理
- 直接抛出，代码中该方法到此为止，不再运行下去
- 捕获处理，试图恢复正常状态，或者进行简单处理然后抛出

###### 异常链：捕获一个异常后，抛出另一个异常，但是想把第一个异常的原始信息保存下来

Throwable的子类在构造器中可以接受一个 cause对象作为参数。只有三种基本的异常类提供了cause(Throwable)参数，他们是 Error / Exception / RuntimeException 


```
java.lang.Throwable
	- java.lang.Exception
		- java.lang.RuntimeException 
	- java.lang.Error 
```

###### RuntimeException

不受检查异常 (运行时异常)
```
if (t == null){
	throw new NullPointerException()
}

```

如果程序每个地方都要判断，代码会很难维护，其实Java会对NULL自动抛出NullPointerException异常，所以不需要额外声明，也被称为 `不受检查异常`

不知道怎么处理异常，但是又不想吞掉，可以将 `受检查异常`信息封装在 `RuntimeException` 中。



Java提供了专门的异常类，所有的异常类均应是java.lang.Throwable的子类。其中，主要分为两大子类:
- java.lang.Error: 其子类表示了Java虚拟机的异常
- java.lang.Exception: 其子类表示了程序运行中的异常

Exception的子类还可以分为两类：
- java.lang.RuntimeException: 其子类表示了运行中的异常，该异常可以不被catch，编译器也能通过。该子类表示的异常，均应该在源代码中避免，比如数组范围的超出等等。
- 非RuntimeException: 其子类表示了程序中不可避免的异常，如文件不存在的FileNotFoundException异常，该异常必须被catch掉或者是在函数头处声明。